name: cs2109s-2220-final
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy=1.23.2 
  - pandas=1.4.3 
  - scikit-learn=1.1.2 
  - pytorch=1.12.1
  - torchvision=0.13.1
  - python=3.10
  - matplotlib=3.5.3